version: '2'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: /data/postgres
    volumes:
        - postgres:/data/postgres
    ports:
      - "5432:5432"
volumes:
  postgres:
