spring:
  jpa:
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
  datasource:
    url: 'jdbc:postgresql://localhost:5432/dfa'
    username: 'dfa_user'
    password: 'dfa_password'
springdoc:
  api-docs:
    path: '/unsafe/api-docs'
jwt:
  secret: 'secret'
  expiration: 1800000
web3j:
  server:
    url: 'http://127.0.0.1:7545'
  gas:
    price: '20000000000'
    limit: '6721975'
contracts:
  factory:
    address: '0x0568B76cAEED066987a40fD545de57F7A2Ade3aa'
  owner:
    address: '0xBa87e8Bcb9C43eDFb7A670b25EA242430F7214E3'
    key: '73ef77b42bffec4991715fc162ea5a16b35e571d209f6faf0544e930c79389f8'

